### ISSUE TITLE
sqlite3.OperationalErrors in hyperparameter tuning

### ISSUE THREAD

**Issue by tsafavi** [Accenture/AmpliGraph#193]
### Description

I am trying to tune ComplEx with ```ampligraph.evaluation.select_best_model_ranking```, but I keep getting various sqlite3.OperationalError exceptions at seemingly random iterations of the grid search saying "no such table: triples_table", "no such table: integrity_check", etc. I am not modifying my directory structure while the code is running. If I understand correctly this error has something to do with the sqlite DB built for the filter triples. 

### Actual Behavior

Example:

```
16it [11:49, 41.87s/it]2020-04-13 06:53:32.031940: W tensorflow/core/framework/op_kernel.cc:1639] Unknown: OperationalError: no such index: triples_table_sp_idx
Traceback (most recent call last):

  File "/x/tsafavi/.local/lib/python3.6/site-packages/tensorflow_core/python/ops/script_ops.py", line 235, in __call__
    ret = func(*args)

  File "/x/tsafavi/.local/lib/python3.6/site-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 594, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/x/tsafavi/.local/lib/python3.6/site-packages/ampligraph/latent_features/models/EmbeddingModel.py", line 1060, in _test_generator
    out, indices_obj, indices_sub = next(batch_iterator)

  File "/x/tsafavi/.local/lib/python3.6/site-packages/ampligraph/datasets/numpy_adapter.py", line 111, in get_next_batch
    participating_objects, participating_subjects = self.filter_adapter.get_participating_entities(out)

  File "/x/tsafavi/.local/lib/python3.6/site-packages/ampligraph/datasets/sqlite_adapter.py", line 405, in get_participating_entities
    cur1.execute(query1)

sqlite3.OperationalError: no such index: triples_table_sp_idx
```

Another example for a different hyperparameter configuration: 

```
42it [35:50, 68.89s/it]2020-04-13 08:00:56.142500: W tensorflow/core/framework/op_kernel.cc:1639] Unknown: OperationalError: no such table: integrity_check
Traceback (most recent call last):

  File "/x/tsafavi/.local/lib/python3.6/site-packages/tensorflow_core/python/ops/script_ops.py", line 235, in __call__
    ret = func(*args)

  File "/x/tsafavi/.local/lib/python3.6/site-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 594, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/x/tsafavi/.local/lib/python3.6/site-packages/ampligraph/latent_features/models/EmbeddingModel.py", line 1060, in _test_generator
    out, indices_obj, indices_sub = next(batch_iterator)

  File "/x/tsafavi/.local/lib/python3.6/site-packages/ampligraph/datasets/numpy_adapter.py", line 111, in get_next_batch
    participating_objects, participating_subjects = self.filter_adapter.get_participating_entities(out)

  File "/x/tsafavi/.local/lib/python3.6/site-packages/ampligraph/datasets/sqlite_adapter.py", line 395, in get_participating_entities
    cur_integrity.execute("SELECT * FROM integrity_check")

sqlite3.OperationalError: no such table: integrity_check
```

### Expected Behavior

Full grid search without errors

### Steps to Reproduce

```
...

X_train, X_valid, X_test = [  # small custom dataset
        load_from_csv(data_dir, fname, sep=sep, header=header)
        for fname in (train, valid, test)]

X_dict = {'train': X_train, 'valid': X_valid, 'test': X_test}

params = {
        'seed': 0,
        'batches_count': [10, 50, 100],  
        'epochs': [500],
        'k': [50, 100, 200],  
        'eta': [1, 5, 10],  
        'loss': ['pairwise', 'nll', 'self_adversarial'],
        'loss_params': {
            'margin': [1, 5],  
            'alpha': [0.5]  
        },
        'embedding_model_params': {
            'negative_corruption_entities': 'all'
        },
        'regularizer': [None, 'LP'],
        'regularizer_params': {
            'p': [3],
            'lambda': [1e-4, 1e-5]
        },
        'optimizer': ['adagrad', 'adam'],
        'optimizer_params': {
            'lr': [0.1, 0.01, 0.0001]
        },
        'verbose': False
}

X_filter = np.concatenate(
        (X_dict['train'], X_dict['valid'], X_dict['test'])
)

return select_best_model_ranking(
        ComplEx,
        X_dict['train'],
        X_dict['valid'],
        X_dict['test'],
        params,
        early_stopping=True,
        early_stopping_params={
            'x_valid': X_dict['valid'],
            'criteria': 'mrr',
            'burn_in': 100,
            'check_interval': 10,
            'stop_interval': 3,
            'x_filter': X_filter,
            'corruption_entities': 'all',
        },
        use_filter=True,
        corrupt_side='s,o',
        verbose=False
)
```

**Comment by sumitpai** [comment]
I tried to reproduce this with standard datasets. however I am not able to reproduce this. Can you set verbose to true for both model selection and in model params and let us know if some of the models train, or do you get the error as soon as you run this?

**Comment by tsafavi** [comment]
I am able to train some models. The error comes intermittently throughout the grid search, and it doesn't seem to be consistent in when/where it shows up.

**Comment by sumitpai** [comment]
Can you also check if this happens during early stopping or during evaluation?

**Comment by tsafavi** [comment]
It only happened during early stopping for me.

**Comment by sumitpai** [comment]
Can you do the following and report the ampligraph version you are using. Ideally you should be on 1.3.1. 

```
import ampligraph
print(ampligraph.__version__)
```

**Comment by tsafavi** [comment]
I do get 1.3.1.

**Comment by sumitpai** [comment]
I am trying to reproduce this issue but I am not able to do so. can you please verify if there are any nan values in your dataset?

**Comment by sumitpai** [comment]
It could also be due to some permission issues. If you run the below snippet you should not get that error. Can you please verify :
```
from ampligraph.datasets import load_wn18rr
from ampligraph.evaluation import select_best_model_ranking
from ampligraph.latent_features import ComplEx
import numpy as np


X_dict = load_wn18rr()

params = {
        'seed': 0,
        'batches_count': [10],  
        'epochs': [10],
        'k': [50],  
        'eta': [1],  
        'loss': ['pairwise'],
        'loss_params': {
            'margin': [1],  
            'alpha': [0.5]  
        },
        'embedding_model_params': {
            'negative_corruption_entities': 'all'
        },
        'regularizer': ['LP'],
        'regularizer_params': {
            'p': [3],
            'lambda': [1e-4]
        },
        'optimizer': ['adam'],
        'optimizer_params': {
            'lr': [0.1]
        },
        'verbose': True
}

X_filter = np.concatenate(
        (X_dict['train'], X_dict['valid'], X_dict['test'])
)

select_best_model_ranking(
        ComplEx,
        X_dict['train'],
        X_dict['valid'],
        X_dict['test'],
        params,
        early_stopping=True,
        early_stopping_params={
            'x_valid': X_dict['valid'],
            'criteria': 'mrr',
            'burn_in': 2,
            'check_interval': 2,
            'stop_interval': 3,
            'x_filter': X_filter,
            'corruption_entities': 'all',
        },
        use_filter=True,
        corrupt_side='s,o',
        verbose=True
)
```

**Comment by tsafavi** [comment]
I can confirm that when I run the code snippet you provided, I don't get any errors. However, I still get errors on the original snippet that I provided with a custom dataset. The dataset does not have any nan values.

**Comment by sumitpai** [comment]
It looks like the error occurs only when early stopping kicks in. You don't get the error while training and evaluation. I will look into this further but it may take some time as I cannot reproduce it on my side.

**Comment by sumitpai** [comment]
I have one more question. What Operating System are you on?

**Comment by tsafavi** [comment]
Ubuntu 18.04.2.

**Comment by sumitpai** [comment]
Sorry. I am unable to reproduce this issue.
