### ISSUE TITLE
Bug in early stopping with ConvE

### ISSUE THREAD

**Issue by tsafavi** [Accenture/AmpliGraph#194]
### Description

When I try to fit a ConvE model with early stopping, an error is raised in ```_perform_early_stopping_test```. It happens for both```'corrupt_side'='o'``` and ```'corrupt_side'='s,o'```.

### Actual Behavior

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/x/tsafavi/.local/lib/python3.6/site-packages/ampligraph/latent_features/models/ConvE.py", line 737, in fit
    raise e
  File "/x/tsafavi/.local/lib/python3.6/site-packages/ampligraph/latent_features/models/ConvE.py", line 728, in fit
    if self._perform_early_stopping_test(epoch):
  File "/x/tsafavi/.local/lib/python3.6/site-packages/ampligraph/latent_features/models/EmbeddingModel.py", line 719, in _perform_early_stopping_test
    ranks.append(list(rank_triple))
TypeError: 'numpy.int32' object is not iterable
```

### Expected Behavior

No error

### Steps to Reproduce

```
import unittest

import numpy as np

from ampligraph.datasets import load_fb15k_237
from ampligraph.latent_features import ConvE
from ampligraph.evaluation import evaluate_performance, \
    mrr_score, hits_at_n_score


class TestConvE(unittest.TestCase):

    def setUp(self):
        self.model = ConvE(
            batches_count=100,
            seed=0,
            epochs=50,
        )

    def test_eval(self):
        X_dict = load_fb15k_237()

        X_filter = np.concatenate(
            (X_dict['train'], X_dict['valid'], X_dict['test']))

        # Fit the model on training and validation set
        self.model.fit(
            X_dict['train'],
            early_stopping=True,
            early_stopping_params={
              'x_valid': X_dict['valid'],
              'criteria': 'mrr',
              'burn_in': 10,
              'check_interval': 10,
              'stop_interval': 3,
              'x_filter': X_filter,
              'corruption_entities': 'all',
              'corrupt_side': 's,o'
          }
        )

        ranks = evaluate_performance(
            X_dict['test'],
            model=self.model, filter_triples=X_filter,
            use_default_protocol=True, verbose=True)

        mrr = mrr_score(ranks)
        hits_10 = hits_at_n_score(ranks, n=10)
        print('MRR: {}'.format(mrr))
        print('Hits@10: {}'.format(hits_10))


if __name__ == '__main__':
    unittest.main()
```

**Comment by NicholasMcCarthy** [comment]
Hi @tsafavi, thanks for the bug report. 

There are two bugs here:

i) The early stopping corrupt_sides parameter was not getting copied to the evaluation config, thus hitting the same error when trying to append to the ranks. 
ii) ConvE does not actually support subject corruptions in early stopping mode, doing so would require a re-write of the current early stopping code just for ConvE.  That the documentation says it does is my fault, it should only work for ```get_ranks()``` and ```evaluate_performance()```. However, subject corruptions with the ConvE model is slightly awkward, and the reported literature performance of ConvE is achieved with object corruptions and reciprocal relations added. 

I have pushed and am testing a fix on branch ```feature/194``` - you can pull that branch down or wait until the next minor release.

**Comment by NicholasMcCarthy** [comment]
Merged to develop on PR 195.
