### ISSUE TITLE
Bug in predictive_performance.py

### ISSUE THREAD

**Issue by lzw950905** [Accenture/AmpliGraph#234]
### Description
When I want to reproduce the experiments in experiments/predictive_performance.py, it always has bug. I use terminal to input 'python predictive_performance.py -d wn18rr/fb15k-237 -m model', some could work, but for many models, it reports bug. (successful eg. wn18rr-complex and distmult, others are wrong)
### Actual Behavior
the bug always:
Traceback (most recent call last):
  File "predictive_performance.py", line 246, in <module>
    main()
  File "predictive_performance.py", line 232, in main
    args.model.upper())
  File "predictive_performance.py", line 119, in run_single_exp
    'check_interval': 50
  File "/home/ziwli/AmpliGraph/ampligraph/latent_features/models/ComplEx.py", line 304, in fit
    super().fit(X, early_stopping, early_stopping_params)
  File "/home/ziwli/AmpliGraph/ampligraph/latent_features/models/EmbeddingModel.py", line 1025, in fit
    raise e
  File "/home/ziwli/AmpliGraph/ampligraph/latent_features/models/EmbeddingModel.py", line 960, in fit
    self.sess_train.run(tf.global_variables_initializer())
  File "/home/ziwli/anaconda3/envs/ampligraph/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/home/ziwli/anaconda3/envs/ampligraph/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/ziwli/anaconda3/envs/ampligraph/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/home/ziwli/anaconda3/envs/ampligraph/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[14505,700] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[node ent_emb/Adam_1/Assign (defined at /home/ziwli/anaconda3/envs/ampligraph/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

### Expected Behavior

I want to run successfully for each model in wn18rr and fb15k-237

**Comment by sumitpai** [comment]
Hi @lzw950905, the issue seems to be related to the model running out of memory on the GPU. We had run the experiments on a Tesla V100 with a memory of 16GB. Probably your GPU is different and cannot allocate the memory. Try reducing the batch count, k or eta until it would fit on your GPU.
